### ISSUE TITLE
Flutter Firebase not working for ios devices

### ISSUE THREAD

**Issue by ShinuMathew** [ShinuMathew/chaiwala420#5]
Launching lib/main.dart on iPhone 12 Pro in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           329.1s
Debug service listening on ws://127.0.0.1:62066/5oUtzGbaxVk=/ws
Syncing files to device iPhone 12 Pro...
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: [core/not-initialized] Firebase has not been correctly initialized. Have you added the "GoogleService-Info.plist" file to the project? 

View the iOS Installation documentation for more information: https://firebase.flutter.dev/docs/installation/ios

#0      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:88:9)
<asynchronous suspension>
#1      Firebase.initializeApp (package:firebase_core/src/firebase.dart:41:31)
<asynchronous suspension>
#2      main (package:chaiwala420/main.dart:10:3)
<asynchronous suspension>

**Comment by ShinuMathew** [comment]
Firebase ios integration setup for flutter project needs to be done separately. Refer https://firebase.flutter.dev/docs/installation/ios/
